### ISSUE TITLE
Feature request: fetch stripe.js on demand

### ISSUE THREAD

**Issue by jamesarosen** [code-corps/ember-stripe-service#20]
Most of our users and most pages in the app _don't_ have anything to do with billing. I'd really like to be able to do something like

``` js
// route:billing
export default Ember.Route.extend({
  stripe: Ember.inject.service(),

  beforeModel: function() {
    return this.get('stripe').fetchJS();
  }
});
```

Where `fetchJS` would (a) return a resolved promise if `window.Stripe` is already defined, or (b) fetch and evaluate `stripe.js` and return a pending Promise that resolves when the library becomes available.

This would let us save a network request and some JS evaluation time for most users.

**Comment by jamesarosen** [comment]
I'm happy to implement this if you think it's a good idea. There would have to be some configuration to tell the addon that it _shouldn't_ inject the `<script>` tag. Alternatively, it could inject something like
```html
<script id='ember-stripe-service-library' type="text/javascript" data-src="https://js.stripe.com/v2/"></script>
```
and then the `service:stripe` would swap `data-src` to `src` to cause the library to load and attach an `onload` handler to get notified when the library loads.

**Comment by buritica** [comment]
I'm not sure how common of a use case this is, but I sort of get what you suggest. I'd guess it's ok to give the option not to load from the beginning, but then there should be a way to tell the service to load it. 

This is sort of lazy instantiation, but I guess you're now possibly deferring the wait time to interaction. A few questions before you go through the effort of making this happen:

- In what cases would window.Stripe already be defined?
- How would you ask the service to proceed with loading stripe once you realize you need stripe in that page? 

Thanks!!

**Comment by jamesarosen** [comment]
> In what cases would window.Stripe already be defined?

If you've already asked the service to load the library and it loaded successfully. This might come up if the user navigated to the billing route, then away, then back. The second time, the billing route would ask the service to ensure Stripe is loaded, which it already is.

> How would you ask the service to proceed with loading stripe once you realize you need stripe in that page?

The API I suggested was `stripeService.fetchJS()`, which returns a promise when the JS library is loaded.

**Comment by buritica** [comment]
hey @jamesarosen sorry for the delay, I think what you suggest makes sense. I've updated the addon a fair bit, mostly cleaning up some stuff and adding better tests. You can go head and send this in so we can see how it behaves.

thanks!

**Comment by jamesarosen** [comment]
One important implementation choice is whether to use [jQuery.getScript](https://api.jquery.com/jquery.getscript/). jQuery is currently a dependency of Ember, but I know there are efforts afoot to reduce that. I'll start out using it and at least keep it isolated.

**Comment by jamesarosen** [comment]
Strike that. `getScript` automatically appends cache-busting parameters. And we want to make sure the evaluation happens within a run-loop. Normally I'd use `ic-ajax`, but this library doesn't currently use that to wrap other calls. (It's probably a good idea, but I've not noticed any problems using it.)

What do you think?

**Comment by jamesarosen** [comment]
OK. There are two possible implementation paths I'm considering:

 1. *opt-out of pre-loading*. The app developer sets `ENV.stripe.deferLoad = true`. In that case, this library emits `<script data-library="stripe-v2" data-src="https://js.stripe.com/v2/"></script>` instead of the normal `<script>` tag. Then, this library first does a `$.ajax` based on `$('script[data-library="stripe-v2"]').data('src')` before any other operations.
 2. *use async+defer*. The library emits `<script type="text/javascript" data-library="stripe-v2" src="https://js.stripe.com/v2/" async defer></script>` at the top of the page. It then uses `$('script[data-library="stripe-v2"]').on('ready')` to get notified when the library is ready. It holds all other operations until that promise resolves.
 3. *never pre-load*. The library doesn't emit a `<script>` tag at all. Instead, it offers a pubic API method, `stripeService.getScript()`, which returns a promise. To get current behavior, an app could just have an initializer that blocks on that promise. This is the largest departure from current behavior since it requires a change from existing clients.
 4. *initializer-pre-load by default*. This is the previous version, but the included initializer does the `stripeService.getScript()` blocking by default. The app developer could opt out with `ENV.stripe.eagerLoad = false;`

I only came up with (4) as I was writing out the others. It's my favorite so far.

**Comment by buritica** [comment]
@slexaxton do you know someone we can talk to at Stripe who can give us some insight into the best way to lazy-load Stripe.js in this addon?

**Comment by SlexAxton** [comment]
It's asynchronous-able like most scripts. Anything that it needs to do before you call it (hidden iframes mostly) it'll queue up before it completes your request.

With jQuery it'd be:

```javascript
$.getScript('https://js.stripe.com/v2/', function() {
  Stripe.card.create...
});
```

Vanilla loaders will look pretty similar.

The key is to not serve it yourself. That has PCI implications.

**Comment by jamesarosen** [comment]
@SlexAxton note that `$.getScript` adds a cache-busting query parameter. See https://api.jquery.com/jquery.getscript/#caching-requests. So we probably *don't* want that, but `$.ajax({ url: '...', cache: true, dataType: 'script' })` would work.

**Comment by SlexAxton** [comment]
Sure. You're welcome to cache bust it if you'd like. That's probably an implementation detail on your end, but I agree with the normal version by default.

**Comment by JoshSmith** [comment]
@jamesarosen if you're still interested in implementing something like #4 I could get behind that, pending what @buritica thinks about this. I think the use case makes sense given efforts lately to only load _exactly_ what the user needs to avoid lots of requests.

**Comment by jamesarosen** [comment]
We're actually in the process of moving away from Stripe, so I probably won't get a chance to write up a PR, though I'm happy to provide thoughts or commentary.

**Comment by buritica** [comment]
i'm closing this, since it seems no one currently has the need for it. will revisit if anyone requires it.

**Comment by ryanto** [comment]
We need this, but it's a low priority for us. Only one of our pages needs stripe, but currently all of our pages to load it. We're happy to take this one on when we have some bandwidth.

**Comment by ryanto** [comment]
I took at shot at lazying loading in https://github.com/code-corps/ember-stripe-service/pull/59
