### ISSUE TITLE
Add Inch-CI

### ISSUE THREAD

**Issue by rileytaylor** [code-corps/ember-stripe-service#48]
Inch CI can crawl documentation and keep us updated on the state of documentation across the project. This is an issue for tracking the steps needed to integrate ember-stripe-service with inch-ci

- [ ] Add `inch.json` and configure to crawl the correct folders
- [ ] Add badge to README
- [ ] Add CI web hook

**Comment by JoshSmith** [comment]
@rileytaylor are you planning on tackling this soon?

**Comment by JoshSmith** [comment]
@rileytaylor pinging again.

**Comment by rileytaylor** [comment]
@joshsmith this was finished by PR #50. Not sure why it wasn't closed by my pr message.
