### ISSUE TITLE
Cannot read property 'assert' of undefined during acceptance test of my app...

### ISSUE THREAD

**Issue by joshuairl** [code-corps/ember-stripe-service#52]
My process works fine when I run it normally but fails during Acceptance test.
Is it possible for you to help me figure out what I'm doing wrong?
I'm kind of new to Ember Acceptance tests so I'm probably missing something simple.

```
Uncaught TypeError: Cannot read property 'assert' of undefined
    at Class.asyncStart (adapter.js:10)
    at Object.asyncStart (ember.debug.js:38454)
    at Object.async (ember.debug.js:37626)
    at fulfill (ember.debug.js:58105)
    at handleMaybeThenable (ember.debug.js:58067)
    at resolve (ember.debug.js:58080)
    at resolvePromise (ember.debug.js:58216)
    at stripe.js:46
    at Object.success ((index):2)
    at Object.<anonymous> ((index):3)
```

**Comment by JoshSmith** [comment]
@joshuairl do you have an example of how you're using it that you can share? If it's nothing that you can put on GitHub to see (or example code), I'd be happy to try and pair with you on it.

**Comment by joshuairl** [comment]
@JoshSmith Wow, that's very kind.  I've never been good at knowing where to breakout an ember-cli into testable segments.  I think that's because I started with Ember POST ember-cli so I've never used Ember without the CLI so I guess all the magic tricks me into thinking it's more complicated than it really is.

I'm going to keep plugging away and maybe it'll work itself out.

If not I'll keep you posted.
If you don't see any reason why this would be a bug, then let's go ahead and close it.

**Comment by JoshSmith** [comment]
@joshuairl it possibly is, but seriously don't have trouble sitting down and pairing. My email is on my profile if you want to just shoot me a quick message.

**Comment by joshuairl** [comment]
@JoshSmith Added you on Screenhero.  We can come up with a decent time to connect.  I'd love to hopefully get my tests passing but only when you have a free moment, and it's no bother of course.

**Comment by JoshSmith** [comment]
@joshuairl was this still an issue?

**Comment by joshuairl** [comment]
As of today, yes.  :-/. Will keep you posted

**Comment by joshuairl** [comment]
Alright... I've done as much cleaning up / scrubbing of my promises as I can and I think they are solid enough to not be causing this assert issue within acceptance tests.

However, it's still happening on stripe.js even though the test technically should pass, it fails on that same line.

https://github.com/code-corps/ember-stripe-service/blob/master/addon/services/stripe.js#L43

```
Uncaught TypeError: Cannot read property 'assert' of undefined
    at Class.asyncStart (adapter.js:10)
    at Object.asyncStart (ember.debug.js:38454)
    at Object.async (ember.debug.js:37626)
    at fulfill (ember.debug.js:58105)
    at handleMaybeThenable (ember.debug.js:58067)
    at resolve (ember.debug.js:58080)
    at resolvePromise (ember.debug.js:58216)
    at stripe.js:46
    at Object.success ((index):2)
    at Object.<anonymous> ((index):3)
```

Should this not be doing `return resolve()` instead of just `resolve()`?

Forgive me, I'm not experienced enough to 100% understand this stuff so I'm just doing my best to report what I'm seeing.

I'll keep trying.

**Comment by JoshSmith** [comment]
@joshuairl can we pair again on this soon? Rest of the week is insane for me, but next week sometime if possible?

**Comment by joshuairl** [comment]
Absolutely!

**Comment by JoshSmith** [comment]
@joshuairl can you send me an email to find a time to do this?

**Comment by buritica** [comment]
closing this issue, since it seems you're looking at it offline
