### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by adambedford** [code-corps/ember-stripe-service#71]
I'm getting a `ReferenceError: document is not defined` error when loading a route with Fastboot that lazy loads Stripe.

Any pointers would be welcomed!

**Comment by snewcomer** [comment]
@adambedford Do you protect loading stripe in FastBoot?  In a node environment, there is no document.  

I'm guessing you want to wait until the browser takes over to get the stripe service (can't do anything with it in node anyways)

```js
if (this.fastboot.isFastBoot) {
  return this.get('stripe').load();
}
```

https://github.com/ember-fastboot/ember-cli-fastboot#fastboot-service

Let me know if you have other questions!

**Comment by adambedford** [comment]
🙌 You were absolutely right!
